page_title: Dano Lee - Home
title: I'm on the trail to the future with AI
description: 데이터와 인공지능 기술이 가져올 미래를 향해 가고 있습니다.
show_downloads: false
google_analytics: UA-121434570-1
theme: jekyll-theme-cayman
og_image: https://d2a08gotq8viav.cloudfront.net/web-pages/images/SKT+Cloud+Inspire2013+Dano+800x800.jpg